#!/bin/sh

if [ "$(uname)" == "Darwin" ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  brew install vim the_silver_searcher tmux go
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  if ! command -v sudo &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive apt install sudo -y
  fi

  if ! command -v ag &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install silversearcher-ag -y
  fi

  if ! command -v vim &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install vim -y
  fi

  if ! command -v tmux &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install tmux -y
  fi

  if ! command -v zsh &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install zsh -y
  fi

  if ! command -v wget &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install wget -y
  fi

  if ! command -v curl &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install curl -y
  fi
  
  if ! command -v go &> /dev/null; then
    sudo rm -fvr /usr/local/go &> /dev/null
    curl -OL https://golang.org/dl/go1.16.7.linux-amd64.tar.gz
    sudo tar -C /usr/local -xvf go1.16.7.linux-amd64.tar.gz
    rm go*.gz
  fi
  
  if command -v go &> /dev/null; then
    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.zshrc
  fi
  
  if ! command -v zsh &> /dev/null; then
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  fi
fi

rm -rvf ~/.zshrc.pre-oh-my-zsh ~/.zshrc ~/.zsh_history ~/.shell.pre-oh-my-zsh .oh-my-zsh

if [ -f "$HOME/.ralias" ] ; then
  rm -f ~/.aliases
fi

if [ -f "$HOME/.gemrc" ] ; then
  rm -f ~/.gemrc
fi
if [ -f "$HOME/.gitconfig" ] ; then
  rm -f ~/.gitconfig
fi
if [ -f "$HOME/.tmux.conf" ] ; then
  rm -f ~/.tmux.conf
fi
if [ -f "$HOME/.zshrc" ] ; then
  rm -f ~/.zshrc
fi
if [ -f "$HOME/.gorc" ] ; then
  rm -f ~/.gorc
fi
if [ -f "$HOME/.pryr" ] ; then
  rm -f ~/.pryr
fi

cp $(pwd)/gemrc ~/.gemrc
cp $(pwd)/gitconfig ~/.gitconfig
cp $(pwd)/tmux.conf ~/.tmux.conf
cp $(pwd)/zshrc ~/.zshrc
cp $(pwd)/gorc ~/.gorc
cp $(pwd)/pryrc ~/.pryrc
cp $(pwd)/alias ~/.ralias
cp $(pwd)/nanorc ~/.nanorc


grep -qxF 'if [ -f ~/.ralias ]; then . ~/.ralias; fi' ~/.bashrc || echo 'if [ -f ~/.ralias ]; then . ~/.ralias; fi' >> ~/.bashrc

grep -qxF 'if [ -f ~/.ralias ]; then . ~/.ralias; fi' ~/.zshrc || echo 'if [ -f ~/.ralias ]; then . ~/.ralias; fi' >> ~/.zshrc



# Clean up old unnecessary files or symlinks
rm -f ~/.vimrc ~/.gvimrc ~/.vimrc.bundles; rm -rf ~/.vim

#personal preference
git config --global pager.branch false

# Clone directly into ~/.vim
git clone https://github.com/reinaldoacosta/vim_dotfiles.git ~/.vim

git clone https://github.com/reinaldoacosta/vim-solarized8.git \
    ~/.vim/pack/themes/opt/solarized8

~/.vim/activate.sh



echo "Everything should be ready to go"
