#!/bin/bash

rm -rfv ~/.vimrc ~/.gvimrc ~/.vimrc.bundles ~/.vim ~/.zshrc.pre-oh-my-zsh ~/.zshrc ~/.zsh_history ~/.shell.pre-oh-my-zsh .oh-my-zsh

if [ "$(uname)" == "Darwin" ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  brew install vim the_silver_searcher tmux go gh nvm neovim
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  if ! command -v sudo &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive apt install sudo -y
  fi

  if ! command -v ag &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install silversearcher-ag -y
  fi

  if ! command -v vim &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install vim -y
  fi

  if ! command -v nvim &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install neovim -y
  fi

  if ! command -v tmux &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install tmux -y
  fi

  if ! command -v zsh &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install zsh -y
  fi

  if ! command -v wget &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install wget -y
  fi

  if ! command -v curl &> /dev/null; then
    DEBIAN_FRONTEND=non_interactive sudo apt install curl -y
  fi

  if ! command -v go &> /dev/null; then
    echo "Installing go..."
    sudo rm -fvr /usr/local/go &> /dev/null
    curl -OL https://go.dev/dl/go1.21.4.linux-amd64.tar.gz
    sudo tar -C /usr/local -xvf go1.21.4.linux-amd64.tar.gz
    rm go*.gz
  fi

  if command -v go &> /dev/null; then
    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.zshrc
  fi

  if ! command -v zsh &> /dev/null; then
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  fi
fi


if [ -f "$HOME/.ralias" ] ; then
  rm -f ~/.aliases
fi

if [ -f "$HOME/.gemrc" ] ; then
  rm -f ~/.gemrc
fi
if [ -f "$HOME/.gitconfig" ] ; then
  rm -f ~/.gitconfig
fi
if [ -f "$HOME/.tmux.conf" ] ; then
  rm -f ~/.tmux.conf
fi
if [ -f "$HOME/.zshrc" ] ; then
  rm -f ~/.zshrc
fi
if [ -f "$HOME/.gorc" ] ; then
  rm -f ~/.gorc
fi
if [ -f "$HOME/.pryr" ] ; then
  rm -f ~/.pryr
fi

cp $(pwd)/gemrc ~/.gemrc
cp $(pwd)/gitconfig ~/.gitconfig
cp $(pwd)/tmux.conf ~/.tmux.conf
cp $(pwd)/zshrc ~/.zshrc
cp $(pwd)/gorc ~/.gorc
cp $(pwd)/pryrc ~/.pryrc
cp $(pwd)/alias ~/.ralias
cp $(pwd)/nanorc ~/.nanorc
#cp $(pwd)/tmux-session-connect ~/.tmux-session-connect


grep -qxF 'if [ -f ~/.ralias ]; then . ~/.ralias; fi' ~/.bashrc || echo 'if [ -f ~/.ralias ]; then . ~/.ralias; fi' >> ~/.bashrc
grep -qxF 'if [ -f ~/.ralias ]; then . ~/.ralias; fi' ~/.zshrc || echo 'if [ -f ~/.ralias ]; then . ~/.ralias; fi' >> ~/.zshrc

# grep -qxF 'if [ -f ~/.tmux-session-connect ]; then . ~/.tmux-session-connect; fi' ~/.bashrc || echo 'if [ -f ~/.tmux-session-connect ]; then . ~/.tmux-session-connect; fi' >> ~/.bashrc
# grep -qxF 'if [ -f ~/.tmux-session-connect ]; then . ~/.tmux-session-connect; fi' ~/.zshrc || echo 'if [ -f ~/.tmux-session-connect ]; then . ~/.tmux-session-connect; fi' >> ~/.zshrc

# Clean up old unnecessary files or symlinks

#personal preference
git config --global pager.branch false
git config --global user.name Reinaldo
git config --global user.email "12644557+reinaldoacosta@users.noreply.github.com"

# Clone directly into ~/.vim
cp -r ./vim ~/.vim
git clone https://github.com/reinaldoacosta/vim-solarized8.git ~/.vim/pack/themes/opt/solarized8
# Install github copilot
git clone https://github.com/github/copilot.vim.git ~/.vim/pack/github/start/copilot.vim

~/.vim/activate.sh

sed -i 's/colorscheme default/colorscheme github_light/g' ~/.vim/vimrc
#download fonts and install them in the system
#the font URL is https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/AnonymousPro/complete/Anonymice%20Nerd%20Font%20Complete%20Mono.ttf

echo -e "\033[0;31mDownload the following font: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/AnonymousPro/complete/Anonymice%20Nerd%20Font%20Complete%20Mono.ttf and install it in the system.\033[0m"
echo -e "\033[0;33mPlease restart your terminal and do not forget to log into Github Copilot in NeoVim.\033[0m"
echo -e "\033[0;32mDone!\033[0m"
