name: remote trigger
on:

  push:
    branches: ["master"]

  workflow_dispatch:
     inputs:
      ubuntu_trigger:
        description: 'Ù‹Ubuntu job which will be triggered'
        required: true
        default: 'ubuntu_trigger'

      ubuntu_trigger_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'reinaldoacosta'

      ubuntu_trigger_repo_github:
        description: 'remote reinaldo ubuntu docker image'
        required: true
        default: 'ubuntu' 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Ubuntu Remote trigger
        run: |
          curl -X POST https://api.github.com/repos/reinaldoacosta/ubuntu/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3
